### ISSUE TITLE
view_inventory

### ISSUE THREAD

**Issue by deronbrowne** [deronbrowne/Bookkeeper-Buddy#8]
@vkee No idea what's wrong [here](https://github.com/deronbrowne/Bookkeeper-Buddy/blob/99d8ef1ffa995256f4bb55024efb7bde52e88a55/Inventory.py#L45). For some reason when I want to view the inventory I've created, it skips the entire for loop and it just goes to the next print statement at line 55.

**Comment by deronbrowne** [comment]
I tried seeing which part of it is running by using "print 'here'" and the strange thing is that it's entering the for loop, but not executing any of the statements there.

**Comment by vkee** [comment]
How can I replicate the issue? (add those to the issues in the future).

You should print out 'x' before entering the loop. Also in the future when using range to generating the indices use xrange, it's faster.

**Comment by vkee** [comment]
You resolved it?

**Comment by deronbrowne** [comment]
Yeah. This was the thing where I was iterating over the list as I changed it.
